---
- hosts: mongo_cluster
  remote_user: emerson
  tasks:
  - name: Install mongodb-server
    apt: name=mongodb-server state=latest
  - name: Install mongodb-clients
    apt: name=mongodb-clients state=latest
  - name: Install mongodb
    apt: name=mongodb state=latest
